package configuration

var Roles = `{
"administrator": {
	"name": "administrator",
	"permissions": [],
	"canAddInUsers": true,
	"isSystemRole": true
},
"authenticated": {
	"name": "authenticated",
	"permissions": [
	"find_article",
	"find_menu",
	"find_link",
	"find_vocabulary",
	"find_term",
	"find_file",
	"find_image",
	"find_user",
	"find_portfolio",
	"find_content",
	"find_company",
	"find_slide",
	"create_contact_message",
	"author_find",
	"find_author",
	"find_businesswire",
	"find_rss",
	"find_blog",
	"find_blog-post",
	"manage_own_blog",
	"find_company-demostracao-financeira-anual",
	"find_company-demostracao-financeira-trimestral",
	"find_symbol",
	"find_page",
	"create_user-error-report",
	"find_finance-price-variation",
	"find_relevant-fact",
	"find_relevant-fact-is",
	"find_relatorio",
	"create_user-alert-trigger",
	"find_user-alert-trigger",
	"find_user-alert-result",
	"find_b3-history",
	"find_b3-history-item",
	"find_b3-history-ibov",
	"find_dino-news",
	"find_cma-news",
	"find_b3-news",
	"find_wallet-investment",
	"create_wallet-investment",
	"findOne_context_widget",
	"find_widget",
	"find_quote-update-news",
	"find_quote-daily-news",
	"find_company-relevant-fact",
	"find_e-books",
	"find_e-book"
	],
	"isSystemRole": true
},
"unAuthenticated": {
	"name": "unAuthenticated",
	"permissions": [
	"find_article",
	"find_menu",
	"find_link",
	"find_vocabulary",
	"find_term",
	"find_file",
	"find_image",
	"find_portfolio",
	"find_content",
	"find_company",
	"find_slide",
	"create_contact_message",
	"author_find",
	"find_author",
	"find_businesswire",
	"find_rss",
	"find_blog",
	"find_blog-post",
	"find_company-demostracao-financeira-anual",
	"find_company-demostracao-financeira-trimestral",
	"find_symbol",
	"find_finance-history",
	"find_page",
	"create_user-error-report",
	"find_finance-price-variation",
	"find_relevant-fact",
	"find_relevant-fact",
	"find_relevant-fact-is",
	"find_relatorio",
	"find_dino-news",
	"find_cma-news",
	"find_b3-news",
	"findOne_context_widget",
	"find_widget",
	"find_quote-update-news",
	"find_quote-daily-news",
	"find_company-relevant-fact"
	],
	"isSystemRole": true
},
"owner": {
	"name": "owner",
	"permissions": [
	"update_article",
	"delete_article",
	"find_user",
	"update_user",
	"update_page",
	"find_user-error-report",
	"find_user-alert-trigger",
	"update_user-alert-trigger",
	"delete_user-alert-trigger",
	"find_user-alert-result",
	"update_wallet-investment",
	"delete_wallet-investment"
	],
	"isSystemRole": true
},
"premium": {
	"name": "premium",
	"permissions": [
	"access_premium_features",
	"find_wallet-investment",
	"create_wallet-investment",
	"view_premium_reports",
	"find_news-premium",
	"add_multiple_alert_triggers",
	"find_e-books",
	"find_e-book"
	],
	"canAddInUsers": true,
	"isSystemRole": false
},
"blog_editor": {
	"name": "blog_editor",
	"canAddInUsers": false,
	"permissions": [
	"update_blog",
	"create_blog-post",
	"update_blog-post",
	"delete_blog-post"
	]
}
}`
